name: "StaticCheck"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run StatiCheck"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"
